# -*- coding: utf-8 -*-
"""New SIT project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-4lsLMrEhIXGubzVxqAn7teM1RMdrg6
"""

class Account:
    def __init__(self, name, startingBalance):
        self.name = name
        self.balance = startingBalance

    def print_account(self):
        print("%s $%.2f" % (self.name, self.balance))


    def withdraw(self, amount):
        self.balance -= amount

    def deposit(self, amount):
        self.balance += amount


account_1 = Account("Fred", 100.0)
account_1.print_account()

account_2 = Account("Jane", 80.0)
account_2.print_account()

num = []
while num != 4 or num > 4:
  try:
      line = input("Select an option:  1. Deposit, 2. Withdraw, 3. Print Account, 4. Quit ")
      num = int(line)

  except:
    print("You must enter a number between 1 and 4")

  else:
    if num > 4 or  num < 1:
      print("You must enter a number between 1 and 4")
       
  finally:
    if num == 1:
      print("How much would you like to deposit? ")
      amount = int(input())
      account_1.deposit(amount)
      account_1.print_account()

    elif num == 2:
      print("How much would you like to withdraw? ")
      amount = int(input())
      account_1.withdraw(amount)
      account_1.print_account()

    elif num == 3:
      account_1.print_account()

    elif num == 4:
      print("Quit!")